AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  exercise

  Sample SAM Template for exercise

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:logs:*:*:*
  GetDataHeroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hero/get_data_hero/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetDataHero:
          Type: Api
          Properties:
            Path: /hero
            Method: get

  GetDataVehiclesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: vehicle/get_data_vehicle/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetDataHero:
          Type: Api
          Properties:
           Path: /vehicles
           Method: get
  GetVehicleByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: vehicle/get_vehicle_by_id/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetDataHero:
          Type: Api
          Properties:
            Path: /get_vehicle_by_id
            Method: get
  CreateDataVehicleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: vehicle/create_vehicle
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateDataVehicle:
          Type: Api
          Properties:
            Path: /create_vehicle
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetDataHeroApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Data Hero function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hero/"
  GetDataHeroFunction:
    Description: "Get Data Hero Function ARN"
    Value: !GetAtt GetDataHeroFunction.Arn
  GetDataVehiclesFunction:
    Description: "Get Data Vehicles Function ARN"
    Value: !GetAtt GetDataVehiclesFunction.Arn
  GetVehicleByIdFunction:
    Description: "Get Data of One Vehicle Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_vehicle_by_id"
  CreateDataVehicleFunction:
    Description: "Insert data of vehicles"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_vehicle"
  LambdaExecutionRoleArn:
    Description: "Lambda Execution Role ARN"
    Value: !GetAtt LambdaExecutionRole.Arn
